version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mv documents/resume.pdf /tmp/pdfs/resume.pdf
            mv documents/coverletter.pdf /tmp/pdfs/coverletter.pdf
      - store_artifacts:
          path: /tmp/pdfs
