version: 2

jobs:
  build:
    docker:
      # Primary container
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p ~/results
            mv examples/cv.pdf /tmp/pdfs
            mv examples/resume.pdf /tmp/pdfs
            mv examples/coverletter.pdf /tmp/pdfs
      - store_artifacts:
          path: /tmp/pdfs
