name: Build LaTeX document

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: documents
        path: documents/*.pdf
