name: Build LaTeX document

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up TeXLive
      uses: teatimeguest/setup-texlive-action@v2
    - name: Check `tlmgr` version
      run: tlmgr --version
    - name: Install deps
      run: sudo apt-get install texlive-xetex
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build LaTeX document
      run: make
