name: Build LaTeX document

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up TeXLive
      uses: paolobrasolin/setup-texlive-action@v1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build LaTeX document
      run: make
